drop database if exists irmng20091116;
create database irmng20091116 CHARACTER SET = latin1;
use irmng20091116;

create table MASTER_FAMLIST (
  FAMILY_ID               varchar(10)   NOT NULL,               
  FAMILY                  varchar(100)  DEFAULT NULL, 
  SOURCE                  varchar(50)   DEFAULT NULL, 
  MOST_RECENT_SOURCE      varchar(50)   DEFAULT NULL, 
  DUPLICATE_FLAG          varchar(1)    DEFAULT NULL, 
  SYNONYM_FLAG            varchar(1)    DEFAULT NULL, 
  IS_SYN_OF_CODE          varchar(10)   DEFAULT NULL, 
  IS_SYN_OF_NAME          varchar(100)  DEFAULT NULL, 
  FAM_SYN_REFERENCE       varchar(500)  DEFAULT NULL, 
  FAM_TAX_REMARKS         varchar(250)  DEFAULT NULL, 
  FAM_EXTANT_FLAG         varchar(6)    DEFAULT NULL, 
  FAM_HABITAT_FLAG        varchar(6)    DEFAULT NULL, 
  FAM_EXTANT_FLAG_SOURCE  varchar(500)  DEFAULT NULL, 
  FAM_HABITAT_FLAG_SOURCE varchar(500)  DEFAULT NULL, 
  FAM_DESCRIPTIVE_INFO    varchar(300)  DEFAULT NULL, 
  DATE_LAST_MODIFIED      varchar(30)   DEFAULT NULL, 
  PERSON_WHO_MODIFIED     varchar(20)   DEFAULT NULL, 
  IRMNG_GROUP             varchar(50)   DEFAULT NULL, 
  COL_HIERARCHY           varchar(250)  DEFAULT NULL, 
  SN2000_HIERARCHY        varchar(250)  DEFAULT NULL, 
  IN_PARKER_FLAG          varchar(1)    DEFAULT NULL, 
  IN_COL_FLAG             varchar(1)    DEFAULT NULL, 
  IN_SN2000_FLAG          varchar(1)    DEFAULT NULL, 
  COL2006_FAM_NO          int(11)       DEFAULT NULL, 
  GENUS_LIST              varchar(4000) DEFAULT NULL, 
  GENUS_LIST2             varchar(4000) DEFAULT NULL, 
  GENUS_LIST3             varchar(4000) DEFAULT NULL, 
  GENUS_LIST_SN2000       varchar(4000) DEFAULT NULL, 
  GENUS_LIST_SN2000_2     varchar(4000) DEFAULT NULL, 
  GENUS_LIST_SN2000_3     varchar(4000) DEFAULT NULL, 
  OTHER_SOURCE_GENERA     varchar(4000) DEFAULT NULL, 
  SUPERKINGDOM            varchar(50)   DEFAULT NULL, 
  KINGDOM                 varchar(50)   DEFAULT NULL, 
  SUBKINGDOM              varchar(50)   DEFAULT NULL, 
  PHYLUM                  varchar(50)   DEFAULT NULL, 
  SUBPHYLUM               varchar(50)   DEFAULT NULL, 
  SUPERCLASS              varchar(50)   DEFAULT NULL, 
  CLASS                   varchar(100)  DEFAULT NULL, 
  SUBCLASS                varchar(50)   DEFAULT NULL, 
  INFRACLASS              varchar(50)   DEFAULT NULL, 
  SUPERORDER              varchar(50)   DEFAULT NULL, 
  ORDERNAME               varchar(50)   DEFAULT NULL, 
  SUBORDER                varchar(50)   DEFAULT NULL, 
  INFRAORDER              varchar(50)   DEFAULT NULL, 
  COHORT                  varchar(50)   DEFAULT NULL, 
  SUBCOHORT               varchar(50)   DEFAULT NULL, 
  DIVISION2               varchar(50)   DEFAULT NULL, 
  GROUPNAME               varchar(50)   DEFAULT NULL, 
  SERIES                  varchar(50)   DEFAULT NULL, 
  TRIBE                   varchar(50)   DEFAULT NULL, 
  SUBTRIBE                varchar(50)   DEFAULT NULL, 
  CLADUS                  varchar(50)   DEFAULT NULL, 
  SUPERFAMILY             varchar(50)   DEFAULT NULL, 
  GROUP2                  varchar(50)   DEFAULT NULL, 
  NOMENCLATURE            varchar(50)   DEFAULT NULL, 
  RESPONSIBILITY          varchar(20)   DEFAULT NULL, 
  TEMP_STUFF              varchar(200)  DEFAULT NULL, 
  QUOTED_VALID_GENERA     int(11)       DEFAULT NULL, 
  QUOTED_VALID_SPECIES    int(11)       DEFAULT NULL, 
  LATEST_IRMNG_GENERA     int(11)       DEFAULT NULL, 
  LATEST_IRMNG_SPECIES    int(11)       DEFAULT NULL, 
  NEAR_MATCH_FAMILY       varchar(100)  DEFAULT NULL, 
  OBIS_CLASS_CODE         varchar(12)   DEFAULT NULL, 
  APHIA_ID                int(11)       DEFAULT NULL, 
  APHIA_AUTH              varchar(150)  DEFAULT NULL, 
  CURRENT_NAME            varchar(1)    DEFAULT NULL, 
  CURRENT_NAME_SOURCE     varchar(80)   DEFAULT NULL, 
  ACTION_ITEMS            varchar(255)  DEFAULT NULL, 
  primary key (FAMILY_ID)
) ENGINE=MyISAM;

load data infile '/data/irmng/raw/OBISAU_MASTER_FAMLIST.csv'
  into table MASTER_FAMLIST
  columns terminated by ',' optionally enclosed by '"'
  ignore 1 lines;
  
create table MASTER_GENLIST (
  GENUS_ID                varchar(15)   NOT NULL,
  GENUS                   varchar(50)   DEFAULT NULL,
  AUTHORITY               varchar(255)  DEFAULT NULL,
  FAMILY_ID               varchar(12)   DEFAULT NULL,
  SOURCE                  varchar(80)   DEFAULT NULL,
  DUPLICATE_FLAG          varchar(1)    DEFAULT NULL,
  SYNONYM_FLAG            varchar(1)    DEFAULT NULL,
  IS_SYN_OF_CODE          varchar(15)   DEFAULT NULL,
  IS_SYN_OF_NAME          varchar(50)   DEFAULT NULL,
  GEN_SYN_REFERENCE       varchar(100)  DEFAULT NULL,
  GEN_TAX_REMARKS         varchar(250)  DEFAULT NULL,
  GEN_EXTANT_FLAG         varchar(6)    DEFAULT NULL,
  GEN_HABITAT_FLAG        varchar(6)    DEFAULT NULL,
  GEN_EXTANT_FLAG_SOURCE  varchar(100)  DEFAULT NULL,
  GEN_HABITAT_FLAG_SOURCE varchar(100)  DEFAULT NULL,
  GEN_DESCRIPTIVE_INFO    varchar(250)  DEFAULT NULL,
  DATE_LAST_MODIFIED      varchar(30)   DEFAULT NULL,
  PERSON_WHO_MODIFIED     varchar(20)   DEFAULT NULL,
  IN_COL_FLAG             varchar(1)    DEFAULT NULL,
  IN_SN2000_FLAG          varchar(1)    DEFAULT NULL,
  SN2000_ID               int(11)       DEFAULT NULL,
  SN2000_PREF_ID          int(11)       DEFAULT NULL,
  SN2000_HABITAT          varchar(50)   DEFAULT NULL,
  SN2000_REMARKS          varchar(200)  DEFAULT NULL,
  NOMENCLATURE            varchar(10)   DEFAULT NULL,
  TEMP_STUFF              varchar(250)  DEFAULT NULL,
  IRMNG_GROUP             varchar(5)    DEFAULT NULL,
  FAMILY                  varchar(60)   DEFAULT NULL,
  TEMP_NUMBER             int(11)       DEFAULT NULL,
  TEMP_ROWNUM             int(11)       DEFAULT NULL,
  IN_ING_FLAG             varchar(1)    DEFAULT NULL,
  IN_NOM_ZOO_FLAG         varchar(1)    DEFAULT NULL,
  IRMNG_HIERARCHY         varchar(250)  DEFAULT NULL,
  IMPORTED_HIERARCHY      varchar(250)  DEFAULT NULL,
  FIRST_AUTH_SURNAME      varchar(50)   DEFAULT NULL,
  ING_ID                  int(11)       DEFAULT NULL,
  ING_AUTH                varchar(120)  DEFAULT NULL,
  ING_STATUS              varchar(250)  DEFAULT NULL,
  STATUS_FINAL            varchar(250)  DEFAULT NULL,
  NEAR_MATCH_NAME         varchar(50)   DEFAULT NULL,
  NEAR_MATCH_LIST         varchar(4000) DEFAULT NULL,
  GEN_LENGTH              int(11)       DEFAULT NULL,
  GENUS_GROUP             varchar(55)   DEFAULT NULL,
  OBIS_CLASS_CODE         varchar(12)   DEFAULT NULL,
  APHIA_ID                int(11)       DEFAULT NULL,
  APHIA_AUTH              varchar(150)  DEFAULT NULL,
  SEARCH_NAME             varchar(50)   DEFAULT NULL,
  QUOTED_VALID_SPECIES    int(11)       DEFAULT NULL,
  LATEST_IRMNG_SPECIES    int(11)       DEFAULT NULL,
  SOUNDEX_NAME            varchar(20)   DEFAULT NULL,
  NEAR_MATCH_2001_NAME    varchar(50)   DEFAULT NULL,
  HOMONYMS_EXIST          varchar(1)    DEFAULT NULL,
  PUBLICATION             varchar(500)  DEFAULT NULL,
  NOM_ZOO_REMARKS         varchar(500)  DEFAULT NULL,
  AUTHORITY_SPECIAL       varchar(255)  DEFAULT NULL,
  AUTHORITY_VARIANT1      varchar(255)  DEFAULT NULL,
  AUTHORITY_VARIANT2      varchar(255)  DEFAULT NULL,
  AUTHORITY_VARIANT3      varchar(255)  DEFAULT NULL,
  AUTHORITY_NO_INITS      varchar(255)  DEFAULT NULL,
  NOMEN_ZOOL_ID           int(11)       DEFAULT NULL,
  NOMEN_ZOOL_AUTH         varchar(255)  DEFAULT NULL,
  NOMEN_ZOOL_AUTH_ADDEND  varchar(100)  DEFAULT NULL,
  AUTH_SPECIAL            varchar(255)  DEFAULT NULL,
  NOMEN_ZOOL_SUPPL_AUTHS  varchar(400)  DEFAULT NULL,
  NOMEN_ZOOL_PUBL         varchar(500)  DEFAULT NULL,
  CROSS_REF_IDS           varchar(50)   DEFAULT NULL,
  BASIONYM_IDS            varchar(50)   DEFAULT NULL,
  NOMENCLAT_STATUS        varchar(250)  DEFAULT NULL,
  CURRENT_NAME            varchar(1)    DEFAULT NULL,
  CURRENT_NAME_SOURCE     varchar(80)   DEFAULT NULL,
  ACTION_ITEMS            varchar(255)  DEFAULT NULL,
  primary key (GENUS_ID)
) ENGINE=MyISAM;

load data infile '/data/irmng/raw/OBISAU_MASTER_GENLIST.csv'
  into table MASTER_GENLIST
  columns terminated by ',' optionally enclosed by '"'
  ignore 1 lines;

create table MASTER_SPLIST (
  SPECIES_ID              varchar(20)   NOT NULL,
  GENUS_ORIG              varchar(50)   DEFAULT NULL,
  SPECIES                 varchar(60)   DEFAULT NULL,
  GENUS_ID                varchar(20)   DEFAULT NULL,
  AUTHORITY               varchar(150)  DEFAULT NULL,
  SOURCE                  varchar(60)   DEFAULT NULL,
  DUPLICATE_FLAG          varchar(10)   DEFAULT NULL,
  SYNONYM_FLAG            varchar(1)    DEFAULT NULL,
  IS_SYN_OF_CODE          varchar(20)   DEFAULT NULL,
  IS_SYN_OF_NAME          varchar(80)   DEFAULT NULL,
  SP_SYN_REFERENCE        varchar(100)  DEFAULT NULL,
  SP_TAX_REMARKS          varchar(150)  DEFAULT NULL,
  SP_EXTANT_FLAG          varchar(6)    DEFAULT NULL,
  SP_HABITAT_FLAG         varchar(6)    DEFAULT NULL,
  SP_EXTANT_FLAG_SOURCE   varchar(100)  DEFAULT NULL,
  SP_HABITAT_FLAG_SOURCE  varchar(100)  DEFAULT NULL,
  SP_DESCRIPTIVE_INFO     varchar(100)  DEFAULT NULL,
  DATE_LAST_MODIFIED      varchar(30)   DEFAULT NULL,
  PERSON_WHO_MODIFIED     varchar(20)   DEFAULT NULL,
  COL2006_SP_NO           int(11)       DEFAULT NULL,
  COL2006_NAME_CODE       varchar(50)   DEFAULT NULL,
  COL2006_FAM_NO          int(11)       DEFAULT NULL,
  COL2006_ACCEPTED_NAME   varchar(50)   DEFAULT NULL,
  COL2006_COMMENTS        varchar(50)   DEFAULT NULL,
  IN_COL_FLAG             varchar(1)    DEFAULT NULL,
  IN_SN2000_FLAG          varchar(1)    DEFAULT NULL,
  TEMP_STUFF              varchar(200)  DEFAULT NULL,
  TEMP_FAMILY             varchar(150)  DEFAULT NULL,
  IRMNG_GROUP             varchar(30)   DEFAULT NULL,
  IRMNG_GROUP_ORIG        varchar(20)   DEFAULT NULL,
  HIERARCHY_ORIG          varchar(120)  DEFAULT NULL,
  TEMP_NUMBER             int(11)       DEFAULT NULL,
  TEMP_ROWNUM             int(11)       DEFAULT NULL,
  LOAD_STATUS             varchar(20)   DEFAULT NULL,
  GENUS_SPECIES           varchar(100)  DEFAULT NULL,
  NEAR_MATCH_GEN_SP       varchar(100)  DEFAULT NULL,
  GENUS_FINAL             varchar(50)   DEFAULT NULL,
  CAAB_CODE               varchar(11)   DEFAULT NULL,
  CAAB_SP_NAME_VARIANT    varchar(50)   DEFAULT NULL,
  CAAB_AUTH_VARIANT       varchar(100)  DEFAULT NULL,
  CAAB_FAM_VARIANT        varchar(50)   DEFAULT NULL,
  SP_LENGTH               int(11)       DEFAULT NULL,
  OBIS_CLASS_CODE         varchar(12)   DEFAULT NULL,
  APHIA_ID                varchar(11)   DEFAULT NULL,
  APHIA_AUTH              varchar(150)  DEFAULT NULL,
  SEARCH_NAME             varchar(60)   DEFAULT NULL,
  SOUNDEX_NAME            varchar(20)   DEFAULT NULL,
  NEAR_MATCH_2001_NAME    varchar(120)  DEFAULT NULL,
  NEAR_MATCH_SP           varchar(60)   DEFAULT NULL,
  GEN_SP_LENGTH           int(11)       DEFAULT NULL,
  NEAR_MATCH_2007_NAME    varchar(120)  DEFAULT NULL,
  TEMP_HIDE_FLAG          varchar(1)    DEFAULT NULL,
  NEAR_MATCHES_PHONETIC   varchar(500)  DEFAULT NULL,
  NEAR_MATCHES_OTHER      varchar(500)  DEFAULT NULL,
  AUTH_ORIG               varchar(150)  DEFAULT NULL,
  YEAR_ORIG               varchar(11)   DEFAULT NULL,
  AUTH_BRACKETS           varchar(2)    DEFAULT NULL,
  REVISER_AUTH            varchar(150)  DEFAULT NULL,
  REVISER_YEAR            varchar(11)   DEFAULT NULL,
  AUTH_ADDENDUM           varchar(100)  DEFAULT NULL,
  STATUS                  varchar(50)   DEFAULT NULL,
  CURRENT_NAME            varchar(150)  DEFAULT NULL,
  CURRENT_NAME_SOURCE     varchar(100)  DEFAULT NULL,
  ACTION_ITMES            varchar(255)  DEFAULT NULL,
  CHRESONYM_FLAG          varchar(1)    DEFAULT NULL,
  primary key (SPECIES_ID)
) ENGINE=MyISAM;

load data infile '/data/irmng/raw/OBISAU_MASTER_SPLIST.csv'
  into table MASTER_SPLIST
  columns terminated by ',' optionally enclosed by '"'
  ignore 1 lines;
