drop database if exists irmng20111014;
create database irmng20111014 CHARACTER SET = utf8;
use irmng20111014;


drop table if exists IRMNG_KINGDOMS;

create table IRMNG_KINGDOMS(
 KINGDOM_ID varchar(10),
 KINGDOM varchar(100),
 SYNONYM_FLAG char(1),
 IS_SYN_OF_CODE varchar(10),
 IS_SYN_OF_NAME varchar(100),
 KINGDOM_SYN_REFERENCE varchar(500),
 KINGDOM_TAX_REMARKS varchar(500),
 TEMP_STUFF varchar(200),
 DATE_LAST_MODIFIED varchar(30),
 NOMENCLATURE varchar(10),
 IRMNG_NUMBER varchar(30),
 OLD_IRMNG_ID varchar(10),
 DATE_CREATED varchar(30),
 DATE_DEPRECATED varchar(30),
 PERSON_WHO_DEPRECATED varchar(100),
 DEPRECATION_REASON varchar(255),
 DEPRECATED_SUCCESSOR varchar(30),
 IS_EXTANT char(1),
 IS_RECENTLY_EXTINCT char(1),
 IS_FOSSIL char(1),
 IS_MARINE char(1),
 IS_BRACKISH char(1),
 IS_FRESHWATER char(1),
 IS_TERRESTRIAL char(1),
 PRIMARY KEY (KINGDOM_ID)
)ENGINE=MyISAM DEFAULT CHARSET=utf8 ;

drop table if exists IRMNG_PHYLA;

create table IRMNG_PHYLA(
 PHYLUM_ID varchar(10),
 PHYLUM varchar(100),
 KINGDOM_ID varchar(10),
 SYNONYM_FLAG char(1),
 IS_SYN_OF_CODE varchar(10),
 IS_SYN_OF_NAME varchar(100),
 PHYLUM_SYN_REFERENCE varchar(500),
 PHYLUM_TAX_REMARKS varchar(200),
 IRMNG_HIERARCHY varchar(250),
 TEMP_STUFF varchar(200),
 DATE_LAST_MODIFIED varchar(30),
 EXTANT_FLAG varchar(6),
 HABITAT_FLAG varchar(6),
 EXTANT_FLAG_SOURCE varchar(500),
 HABITAT_FLAG_SOURCE varchar(500),
 NOMENCLATURE varchar(10),
 CURRENT_NAME varchar(1),
 CURRENT_NAME_SOURCE varchar(80),
 AUTHORITY varchar(100),
 AUTHORITY_SPECIAL varchar(100),
 AUTHORITY_BOT_ABBREV varchar(50),
 HOMONYM_FLAG varchar(6),
 IRMNG_NUMBER varchar(30),
 OLD_IRMNG_ID varchar(10),
 DATE_CREATED varchar(30),
 DATE_DEPRECATED varchar(30),
 PERSON_WHO_DEPRECATED varchar(100),
 DEPRECATION_REASON varchar(255),
 DEPRECATED_SUCCESSOR varchar(30),
 IS_EXTANT char(1),
 IS_RECENTLY_EXTINCT char(1),
 IS_FOSSIL char(1),
 IS_MARINE char(1),
 IS_BRACKISH char(1),
 IS_FRESHWATER char(1),
 IS_TERRESTRIAL char(1),
 PRIMARY KEY (PHYLUM_ID)
)ENGINE=MyISAM DEFAULT CHARSET=utf8 ;

drop table if exists IRMNG_CLASSES;

create table IRMNG_CLASSES(
 CLASS_ID varchar(10),
 CLASS varchar(100),
 PHYLUM_ID varchar(10),
 SYNONYM_FLAG char(1),
 IS_SYN_CODE varchar(10),
 IS_SYN_OF_NAME varchar(100),
 CLASS_SYN_REFERENCE varchar(500),
 CLASS_TAX_REMARKS varchar(250),
 IRMNG_HIERARCHY varchar(250),
 TEMP_STUFF varchar(200),
 DATE_LAST_MODIFIED varchar(30),
 EXTANT_FLAG varchar(6),
 HABITAT_FLAG varchar(6),
 EXTANT_FLAG_SOURCE varchar(500),
 HABITAT_FLAG_SOURCE varchar(500),
 NOMENCLATURE varchar(10),
 CURRENT_NAME varchar(1),
 CURRENT_NAME_SOURCE varchar(80),
 AUTHORITY varchar(100),
 AUTHORITY_SPECIAL varchar(100),
 AUTHORITY_BOT_ABBREV varchar(50),
 HOMONYM_FLAG varchar(6),
 IRMNG_NUMBER varchar(30),
 OLD_IRMNG_ID varchar(10),
 IRMNG_GROUP varchar(10),
 DATE_CREATED varchar(30),
 DATE_DEPRECATED varchar(30),
 PERSON_WHO_DEPRECATED varchar(100),
 DEPRECATION_REASON varchar(255),
 DEPRECATED_SUCCESSOR varchar(30),
 IS_EXTANT char(1),
 IS_RECENTLY_EXTINCT char(1),
 IS_FOSSIL char(1),
 IS_MARINE char(1),
 IS_BRACKISH char(1),
 IS_FRESHWATER char(1),
 IS_TERRESTRIAL char(1),
 PRIMARY KEY (CLASS_ID)
)ENGINE=MyISAM DEFAULT CHARSET=utf8 ;

drop table if exists IRMNG_ORDERS;

create table IRMNG_ORDERS(
 ORDER_ID varchar(10),
 ORDERNAME varchar(100),
 CLASS_ID varchar(10),
 SYNONYM_FLAG char(1),
 IS_SYN_CODE varchar(10),
 IS_SYN_OF_NAME varchar(100),
 ORDER_SYN_REFERENCE varchar(500),
 ORDER_TAX_REMARKS varchar(250),
 IRMNG_HIERARCHY varchar(250),
 TEMP_STUFF varchar(200),
 DATE_LAST_MODIFIED varchar(30),
 EXTANT_FLAG varchar(6),
 HABITAT_FLAG varchar(6),
 EXTANT_FLAG_SOURCE varchar(500),
 HABITAT_FLAG_SOURCE varchar(500),
 NOMENCLATURE varchar(10),
 CURRENT_NAME varchar(1),
 CURRENT_NAME_SOURCE varchar(80),
 AUTHORITY varchar(100),
 AUTHORITY_SPECIAL varchar(100),
 AUTHORITY_BOT_ABBREV varchar(50),
 HOMONYM_FLAG varchar(6),
 IRMNG_NUMBER varchar(30),
 OLD_IRMNG_ID varchar(10),
 IRMNG_GROUP varchar(10),
 DATE_CREATED varchar(30),
 DATE_DEPRECATED varchar(30),
 PERSON_WHO_DEPRECATED varchar(100),
 DEPRECATION_REASON varchar(255),
 DEPRECATED_SUCCESSOR varchar(30),
 IS_EXTANT char(1),
 IS_RECENTLY_EXTINCT char(1),
 IS_FOSSIL char(1),
 IS_MARINE char(1),
 IS_BRACKISH char(1),
 IS_FRESHWATER char(1),
 IS_TERRESTRIAL char(1),
 PRIMARY KEY (ORDER_ID)
)ENGINE=MyISAM DEFAULT CHARSET=utf8 ;

DROP TABLE if exists MASTER_FAMLIST;

CREATE TABLE `MASTER_FAMLIST` (
  `FAMILY_ID` varchar(10) NOT NULL,
  `FAMILY` varchar(100) default NULL,
  `SOURCE` varchar(50) default NULL,
  `MOST_RECENT_SOURCE` varchar(50) default NULL,
  `DUPLICATE_FLAG` varchar(1) default NULL,
  `SYNONYM_FLAG` varchar(1) default NULL,
  `IS_SYN_OF_CODE` varchar(10) default NULL,
  `IS_SYN_OF_NAME` varchar(100) default NULL,
  `FAM_SYN_REFERENCE` varchar(500) default NULL,
  `FAM_TAX_REMARKS` varchar(250) default NULL,
  `FAM_EXTANT_FLAG` varchar(6) default NULL,
  `FAM_HABITAT_FLAG` varchar(6) default NULL,
  `FAM_EXTANT_FLAG_SOURCE` varchar(500) default NULL,
  `FAM_HABITAT_FLAG_SOURCE` varchar(500) default NULL,
  `FAM_DESCRIPTIVE_INFO` varchar(300) default NULL,
  `DATE_LAST_MODIFIED` varchar(30) default NULL,
  `PERSON_WHO_MODIFIED` varchar(20) default NULL,
  `IRMNG_GROUP` varchar(50) default NULL,
  `COL_HIERARCHY` varchar(250) default NULL,
  `SN2000_HIERARCHY` varchar(250) default NULL,
  `IN_PARKER_FLAG` varchar(1) default NULL,
  `IN_COL_FLAG` varchar(1) default NULL,
  `IN_SN2000_FLAG` varchar(1) default NULL,
  `COL2006_FAM_NO` int(11) default NULL,
  `SUPERKINGDOM` varchar(50) default NULL,
  `KINGDOM` varchar(50) default NULL,
  `SUBKINGDOM` varchar(50) default NULL,
  `PHYLUM` varchar(50) default NULL,
  `SUBPHYLUM` varchar(50) default NULL,
  `SUPERCLASS` varchar(50) default NULL,
  `CLASS` varchar(100) default NULL,
  `SUBCLASS` varchar(50) default NULL,
  `INFRACLASS` varchar(50) default NULL,
  `SUPERORDER` varchar(50) default NULL,
  `ORDERNAME` varchar(50) default NULL,
  `SUBORDER` varchar(50) default NULL,
  `INFRAORDER` varchar(50) default NULL,
  `COHORT` varchar(50) default NULL,
  `SUBCOHORT` varchar(50) default NULL,
  `DIVISION2` varchar(50) default NULL,
  `GROUPNAME` varchar(50) default NULL,
  `SERIES` varchar(50) default NULL,
  `TRIBE` varchar(50) default NULL,
  `SUBTRIBE` varchar(50) default NULL,
  `CLADUS` varchar(50) default NULL,
  `SUPERFAMILY` varchar(50) default NULL,
  `GROUP2` varchar(50) default NULL,
  `NOMENCLATURE` varchar(50) default NULL,
  `RESPONSIBILITY` varchar(20) default NULL,
  `TEMP_STUFF` varchar(200) default NULL,
  `QUOTED_VALID_GENERA` int(11) default NULL,
  `QUOTED_VALID_SPECIES` int(11) default NULL,
  `LATEST_IRMNG_GENERA` int(11) default NULL,
  `LATEST_IRMNG_SPECIES` int(11) default NULL,
  `NEAR_MATCH_FAMILY` varchar(100) default NULL,
  `OBIS_CLASS_CODE` varchar(12) default NULL,
  `APHIA_ID` int(11) default NULL,
  `APHIA_AUTH` varchar(150) default NULL,
  `CURRENT_NAME` varchar(1) default NULL,
  `CURRENT_NAME_SOURCE` varchar(80) default NULL,
  `ACTION_ITEMS` varchar(255) default NULL,
  SEARCH_NAME varchar(100) default NULL,
  FAM_LENGTH int(11) default NULL,
  ORDER_ID varchar(10) default NULL,
  NOMENCLATURAL_STATUS  varchar(250) default NULL,
  TAXONOMIC_STATUS varchar(100) default NULL,
  AUTHORITY varchar(150) default NULL,
  AUTHORITY_SPECIAL varchar(255) default NULL,
  PUBLICATION varchar(200) default NULL,
  IRMNG_NUMBER varchar(30),
  OLD_IRMNG_ID varchar(10),
  DATE_CREATED varchar(30),
  DATE_DEPRECATED varchar(30),
  PERSON_WHO_DEPRECATED varchar(100),
  DEPRECATION_REASON varchar(255),
  DEPRECATED_SUCCESSOR varchar(30),
  IS_EXTANT char(1),
  IS_RECENTLY_EXTINCT char(1),
  IS_FOSSIL char(1),
  IS_MARINE char(1),
  IS_BRACKISH char(1),
  IS_FRESHWATER char(1),
  IS_TERRESTRIAL char(1),
  HOMONYM_FLAG varchar(6),
  PRIMARY KEY  (`FAMILY_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ;

DROP TABLE if exists MASTER_GENLIST;

CREATE TABLE `MASTER_GENLIST` (
  `GENUS_ID` varchar(15) NOT NULL,
  `GENUS` varchar(50) default NULL,
  `AUTHORITY` varchar(255) default NULL,
  `FAMILY_ID` varchar(12) default NULL,
  `SOURCE` varchar(120) default NULL,
  `DUPLICATE_FLAG` varchar(1) default NULL,
  `SYNONYM_FLAG` varchar(1) default NULL,
  `IS_SYN_OF_CODE` varchar(15) default NULL,
  `IS_SYN_OF_NAME` varchar(50) default NULL,
  `GEN_SYN_REFERENCE` varchar(100) default NULL,
  `GEN_TAX_REMARKS` varchar(250) default NULL,
  `GEN_EXTANT_FLAG` varchar(6) default NULL,
  `GEN_HABITAT_FLAG` varchar(6) default NULL,
  `GEN_EXTANT_FLAG_SOURCE` varchar(100) default NULL,
  `GEN_HABITAT_FLAG_SOURCE` varchar(100) default NULL,
  `GEN_DESCRIPTIVE_INFO` varchar(250) default NULL,
  `DATE_LAST_MODIFIED` varchar(30) default NULL,
  `PERSON_WHO_MODIFIED` varchar(20) default NULL,
  `IN_COL_FLAG` varchar(1) default NULL,
  `IN_SN2000_FLAG` varchar(1) default NULL,
  `SN2000_ID` int(11) default NULL,
  `SN2000_PREF_ID` int(11) default NULL,
  `SN2000_HABITAT` varchar(50) default NULL,
  `SN2000_REMARKS` varchar(200) default NULL,
  `NOMENCLATURE` varchar(10) default NULL,
  `TEMP_STUFF` varchar(250) default NULL,
  `IRMNG_GROUP` varchar(5) default NULL,
  `FAMILY` varchar(60) default NULL,
  `TEMP_NUMBER` int(11) default NULL,
  `TEMP_ROWNUM` int(11) default NULL,
  `IN_ING_FLAG` varchar(1) default NULL,
  `IN_NOM_ZOO_FLAG` varchar(1) default NULL,
  `IRMNG_HIERARCHY` varchar(250) default NULL,
  `IMPORTED_HIERARCHY` varchar(250) default NULL,
  `FIRST_AUTH_SURNAME` varchar(50) default NULL,
  `ING_ID` int(11) default NULL,
  `ING_AUTH` varchar(120) default NULL,
  `ING_STATUS` varchar(250) default NULL,
  `STATUS_FINAL` varchar(250) default NULL,
  `NEAR_MATCH_NAME` varchar(50) default NULL,
  `NEAR_MATCH_LIST` text default NULL,
  `GEN_LENGTH` int(11) default NULL,
  `GENUS_GROUP` varchar(55) default NULL,
  `OBIS_CLASS_CODE` varchar(12) default NULL,
  `APHIA_ID` int(11) default NULL,
  `APHIA_AUTH` varchar(150) default NULL,
  `SEARCH_NAME` varchar(50) default NULL,
  `QUOTED_VALID_SPECIES` int(11) default NULL,
  `LATEST_IRMNG_SPECIES` int(11) default NULL,
  `SOUNDEX_NAME` varchar(20) default NULL,
  `NEAR_MATCH_2001_NAME` varchar(50) default NULL,
  `HOMONYMS_EXIST` varchar(1) default NULL,
  `PUBLICATION` varchar(500) default NULL,
  `NOM_ZOO_REMARKS` varchar(500) default NULL,
  `AUTHORITY_SPECIAL` varchar(255) default NULL,
  `AUTHORITY_VARIANT1` varchar(255) default NULL,
  `AUTHORITY_VARIANT2` varchar(255) default NULL,
  `AUTHORITY_VARIANT3` varchar(255) default NULL,
  `AUTHORITY_NO_INITS` varchar(255) default NULL,
  `NOMEN_ZOOL_ID` int(11) default NULL,
  `NOMEN_ZOOL_AUTH` varchar(255) default NULL,
  `NOMEN_ZOOL_AUTH_ADDEND` varchar(100) default NULL,
  `AUTH_EXTENSION` varchar(255) default NULL,
  `NOMEN_ZOOL_SUPPL_AUTHS` varchar(400) default NULL,
  `NOMEN_ZOOL_PUBL` varchar(500) default NULL,
  `VARIANT_OF_CODE` varchar(50) default NULL,
  `BASIONYM_IDS` varchar(50) default NULL,
  `NOMENCLAT_STATUS` varchar(250) default NULL,
  `CURRENT_NAME` varchar(1) default NULL,
  `CURRENT_NAME_SOURCE` varchar(80) default NULL,
  `ACTION_ITEMS` varchar(255) default NULL,
  VALID_SUB_GEN_FLAG varchar(1) default NULL,
  REF_TITLE_ENGLISH varchar(500) default NULL,
  REF_TITLE_OTHER_LANG varchar(500) default NULL,
  REF_AUTHORS varchar(500) default NULL,
  REF_PUBLICATION varchar(500) default NULL,
  REF_VOLUME varchar(30) default NULL,
  REF_ISSUE varchar(30) default NULL,
  REF_PAGES varchar(30) default NULL,
  REF_STARTED_DATE varchar(30) default NULL,
  REF_STARTED_YEAR int(11) default NULL,
  REF_COMMENTS varchar(100) default NULL,
  NAMED_VERIFIED_SOURCE varchar(100) default NULL,
  FAMILY_VERIFIED_SOURCE varchar(100) default NULL,
  HOMONYMS_LIST text default NULL,
  PHONETIC_MATCHES_LIST text default NULL,
  ED1_MATCHES_LIST text default NULL,
  ED2_MATCHES_LIST text default NULL,
  ED3_MATCHES_LIST text default NULL,
  ORIG_DESC_URL varchar(100) default NULL,
  CROSS_REF_ID1 varchar(12) default NULL,
  CROSS_REF_ID2 varchar(12) default NULL,
  CROSS_REF_ID3 varchar(12) default NULL,
  TAXONOMIC_STATUS varchar(100) default NULL,
  SUCCESSOR_TO_CODE varchar(12) default NULL,
  SUBFAMILY varchar(30) default NULL,
  AUTHORITY_BOT_ABBREV varchar(50),
  KEW_LIST_FAMILY varchar(50),
  TYPE_SPECIES_AS_CITED varchar(100),
  GENUS_PREFIX varchar(10),
  HOMONYM_FLAG varchar(6),
  REF_NUMBER varchar(10),
  IRMNG_NUMBER varchar(30),
  OLD_IRMNG_ID varchar(10),
  DATE_CREATED varchar(30),
  DATE_DEPRECATED varchar(30),
  PERSON_WHO_DEPRECATED varchar(100),
  DEPRECATION_REASON varchar(255),
  DEPRECATED_SUCCESSOR varchar(30),
  IS_EXTANT char(1),
  IS_RECENTLY_EXTINCT char(1),
  IS_FOSSIL char(1),
  IS_MARINE char(1),
  IS_BRACKISH char(1),
  IS_FRESHWATER char(1),
  IS_TERRESTRIAL char(1),
  PRIMARY KEY  (`GENUS_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ;

drop table if exists MASTER_SPLIST;

CREATE TABLE `MASTER_SPLIST` (
  `SPECIES_ID` varchar(20) NOT NULL,
  `GENUS_ORIG` varchar(50) default NULL,
  `SPECIES` varchar(60) default NULL,
  `GENUS_ID` varchar(20) default NULL,
  `AUTHORITY` varchar(150) default NULL,
  `SOURCE` varchar(60) default NULL,
  `DUPLICATE_FLAG` varchar(10) default NULL,
  `SYNONYM_FLAG` varchar(1) default NULL,
  `IS_SYN_OF_CODE` varchar(20) default NULL,
  `IS_SYN_OF_NAME` varchar(80) default NULL,
  `SP_SYN_REFERENCE` varchar(100) default NULL,
  `SP_TAX_REMARKS` varchar(150) default NULL,
  `SP_EXTANT_FLAG` varchar(6) default NULL,
  `SP_HABITAT_FLAG` varchar(6) default NULL,
  `SP_EXTANT_FLAG_SOURCE` varchar(100) default NULL,
  `SP_HABITAT_FLAG_SOURCE` varchar(100) default NULL,
  `SP_DESCRIPTIVE_INFO` varchar(100) default NULL,
  `DATE_LAST_MODIFIED` varchar(30) default NULL,
  `PERSON_WHO_MODIFIED` varchar(20) default NULL,
  `COL2006_SP_NO` int(11) default NULL,
  `COL2006_NAME_CODE` varchar(50) default NULL,
  `COL2006_FAM_NO` int(11) default NULL,
  `COL2006_ACCEPTED_NAME` varchar(50) default NULL,
  `COL2006_COMMENTS` varchar(50) default NULL,
  `IN_COL_FLAG` varchar(1) default NULL,
  `IN_SN2000_FLAG` varchar(1) default NULL,
  `TEMP_STUFF` varchar(200) default NULL,
  `TEMP_FAMILY` varchar(150) default NULL,
  `IRMNG_GROUP` varchar(30) default NULL,
  `IRMNG_GROUP_ORIG` varchar(20) default NULL,
  `HIERARCHY_ORIG` varchar(120) default NULL,
  `TEMP_NUMBER` int(11) default NULL,
  `TEMP_ROWNUM` int(11) default NULL,
  `LOAD_STATUS` varchar(20) default NULL,
  `GENUS_SPECIES` varchar(100) default NULL,
  `NEAR_MATCH_GEN_SP` varchar(100) default NULL,
  `GENUS_FINAL` varchar(50) default NULL,
  `CAAB_CODE` varchar(11) default NULL,
  `CAAB_SP_NAME_VARIANT` varchar(50) default NULL,
  `CAAB_AUTH_VARIANT` varchar(100) default NULL,
  `CAAB_FAM_VARIANT` varchar(50) default NULL,
  `SP_LENGTH` int(11) default NULL,
  `OBIS_CLASS_CODE` varchar(12) default NULL,
  `APHIA_ID` varchar(11) default NULL,
  `APHIA_AUTH` varchar(150) default NULL,
  `SEARCH_NAME` varchar(60) default NULL,
  `SOUNDEX_NAME` varchar(20) default NULL,
  `NEAR_MATCH_2001_NAME` varchar(120) default NULL,
  `NEAR_MATCH_SP` varchar(60) default NULL,
  `GEN_SP_LENGTH` int(11) default NULL,
  `NEAR_MATCH_2007_NAME` varchar(120) default NULL,
  `TEMP_HIDE_FLAG` varchar(1) default NULL,
  `NEAR_MATCHES_PHONETIC` varchar(500) default NULL,
  `NEAR_MATCHES_OTHER` varchar(500) default NULL,
  `AUTH_ORIG` varchar(150) default NULL,
  `YEAR_ORIG` varchar(11) default NULL,
  `AUTH_BRACKETS` varchar(2) default NULL,
  `REVISER_AUTH` varchar(150) default NULL,
  `REVISER_YEAR` varchar(11) default NULL,
  `AUTH_ADDENDUM` varchar(100) default NULL,
  `STATUS` varchar(50) default NULL,
  `CURRENT_NAME` varchar(150) default NULL,
  `CURRENT_NAME_SOURCE` varchar(100) default NULL,
  `ACTION_ITMES` varchar(255) default NULL,
  `CHRESONYM_FLAG` varchar(1) default NULL,
  SPECIALIST_NAME varchar(200) default NULL,
  NOMENCLATURAL_STATUS varchar(250) default NULL,
  TAXONOMIC_STATUS varchar(100) default NULL,
  AUTHORITY_SPECIAL varchar(255) default NULL,
  HOMONYM_FLAG varchar(1) default NULL,
  TEMP_HIDE_REASON varchar(60) default NULL,
  NOMENCLATURE varchar(10),
  IRMNG_NUMBER varchar(30),
  OLD_IRMNG_ID varchar(10),
  DATE_CREATED varchar(30),
  DATE_DEPRECATED varchar(30),
  PERSON_WHO_DEPRECATED varchar(100),
  DEPRECATION_REASON varchar(255),
  DEPRECATED_SUCCESSOR varchar(30),
  IS_EXTANT char(1),
  IS_RECENTLY_EXTINCT char(1),
  IS_FOSSIL char(1),
  IS_MARINE char(1),
  IS_BRACKISH char(1),
  IS_FRESHWATER char(1),
  IS_TERRESTRIAL char(1),
  PRIMARY KEY  (`SPECIES_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ;


load data infile '/data/irmng/IRMNG_KINGDOMS.csv'
IGNORE INTO TABLE IRMNG_KINGDOMS
FIELDS OPTIONALLY ENCLOSED BY '"' terminated by ',' 
LINES TERminated by '\r\n'
ignore 1 lines;

load data infile '/data/irmng/IRMNG_PHYLA.csv'
IGNORE INTO TABLE IRMNG_PHYLA
FIELDS OPTIONALLY ENCLOSED BY '"' terminated by ',' 
LINES TERminated by '\r\n'
ignore 1 lines;

load data infile '/data/irmng/IRMNG_CLASSES.csv'
IGNORE INTO TABLE IRMNG_CLASSES
FIELDS OPTIONALLY ENCLOSED BY '"' terminated by ',' 
LINES TERminated by '\r\n'
ignore 1 lines;

load data infile '/data/irmng/IRMNG_ORDERS.csv'
IGNORE INTO TABLE IRMNG_ORDERS
FIELDS OPTIONALLY ENCLOSED BY '"' terminated by ',' 
LINES TERminated by '\r\n'
ignore 1 lines;

load data infile '/data/irmng/MASTER_FAMLIST.csv'
IGNORE INTO TABLE MASTER_FAMLIST
FIELDS OPTIONALLY ENCLOSED BY '"' terminated by ',' 
LINES TERminated by '\r\n'
ignore 1 lines;

load data infile '/data/irmng/MASTER_GENLIST_utf8.csv'
IGNORE INTO TABLE MASTER_GENLIST
FIELDS OPTIONALLY ENCLOSED BY '"' terminated by ',' 
LINES TERminated by '\r\n'
ignore 1 lines;


load data infile '/data/irmng/MASTER_SPLIST_utf8.csv'
IGNORE INTO TABLE MASTER_SPLIST
FIELDS OPTIONALLY ENCLOSED BY '"' terminated by ',' 
LINES TERminated by '\r\n'
ignore 1 lines;


